名字: Upstream Sync

permissions:
    contents: 撰写

on:
    schedule:
        - cron: '0 */2 * * *'        # 每 2 小时触发（UTC）
    workflow_dispatch:

jobs:
    sync_with_upstream:
        名字: Sync with Upstream
        runs-on: ubuntu-latest
        if: ${{ github.event.repository.fork }}

        steps:
            - 名字: Checkout target repo
              uses: actions/checkout@v3

            - 名字: Sync Upstream
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
              with:
                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                  upstream_sync_repo: mursor1985/LIVE
                  upstream_sync_branch: main
                  target_sync_branch: main
                  test_mode: false

            - 名字: Check for Failure
              if: failure()
              run: |
                  echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork."
                  exit 1
